# Generated by Django 5.2.7 on 2025-11-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cloud_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='direct_url',
        ),
        migrations.AddField(
            model_name='video',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
